import jsPDF from "jspdf";

export type TxnPdf = {
  id: string;
  date_received: string;
  items: { name: string; quantity: number; unit: string }[];
  status: string;
  customer: { name: string; ration_id: string } | null;
  distributor: { name: string; ration_id: string } | null;
};

export function downloadTransactionPdf(t: TxnPdf) {
  const doc = new jsPDF();
  const w = doc.internal.pageSize.getWidth();

  // Header bar
  doc.setFillColor(36, 50, 120);
  doc.rect(0, 0, w, 24, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("PUBLIC DISTRIBUTION SYSTEM", 14, 15);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text("Official Transaction Receipt", w - 14, 15, { align: "right" });

  doc.setTextColor(20, 20, 20);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("Transaction Receipt", 14, 38);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  let y = 50;
  const line = (label: string, value: string) => {
    doc.setFont("helvetica", "bold"); doc.text(label, 14, y);
    doc.setFont("helvetica", "normal"); doc.text(value, 70, y);
    y += 7;
  };
  line("Transaction ID:", t.id);
  line("Date & Time:", new Date(t.date_received).toLocaleString());
  line("Recipient:", `${t.customer?.name ?? "—"} (${t.customer?.ration_id ?? "—"})`);
  line("Distributor:", `${t.distributor?.name ?? "—"} (${t.distributor?.ration_id ?? "—"})`);
  line("Status:", t.status);

  y += 5;
  doc.setFont("helvetica", "bold");
  doc.text("Items Distributed", 14, y); y += 4;
  doc.setDrawColor(180); doc.line(14, y, w - 14, y); y += 6;

  doc.setFont("helvetica", "bold");
  doc.text("Item", 14, y); doc.text("Quantity", 110, y); doc.text("Unit", 160, y); y += 4;
  doc.line(14, y, w - 14, y); y += 6;
  doc.setFont("helvetica", "normal");
  for (const it of t.items) {
    doc.text(it.name, 14, y);
    doc.text(String(it.quantity), 110, y);
    doc.text(it.unit, 160, y);
    y += 6;
  }

  doc.setFontSize(8);
  doc.setTextColor(120);
  doc.text("Generated by Public Distribution System • Computer-generated receipt", w / 2, 285, { align: "center" });

  const filename = `Transaction_${t.id.slice(0, 8)}_${new Date(t.date_received).toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
}
